services:
  cockroachdb:
    image: "cockroachdb/cockroach:latest-v23.1"
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    restart: unless-stopped
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "${PWD}/minio:/data"
    command: "server /data --console-address :9001"
    restart: unless-stopped
