services:
  cockroachdb:
    image: "cockroachdb/cockroach:latest-v23.1"
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    restart: unless-stopped